# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 561a1faf7d675fb54743979c0c37618e43456ce45e83e7f6743d990900e81ec18b3293b94860e985e7aea8d91913c646ca2c38236ca83a725947a0ef11ca77ea

test:
  secret_key_base: e549c1dd61a066c32269f02d47d119569647bf715d96706b4d5feadff2d81c48ae3d7d59df48509422e67ae0b05c98d9cde921576f4d97db305d08009a28178c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
